language: python
python: 
  - "2.7"
  - "3.4"

secure: "pw4JIDEHtZyhoJCGoaIwm8XpBjZ+qUehoeQc3taN5mubL/eWrONgISc3iAtSHWF4UUx4IvzV48rK+LNGvJU4ILjZiHQbSxNU+noU2Jip4FLZ3KwRPoKptM8NPG17RDOlLpU2+hNmK3aZd7YKUVlAAFElPhXKh2H6SmjVG87q2uRg2f8XVg00xvuHDzS6Ae2pdAkAf4q0RyrJ/6QxOhxVSAdxxLfCb8EtXKvxPC2lKUpmdtqz7tXOkXOb0sYPIyUQw3mD9k4vF28ASIVGHm1+rGCSC6IOMHIWN3R6S39LRPrw8XfdQudCp/DrkQ9iJQx88XSHZX0v9Sk/fT99ZDdMjL082HiITJeU2/lxa13/dovJsiQ1KARS90WhPZfZSOHEMJJh1Y7hBVvWwFAClYQReu2Er1BupmE5b33vJVnM8f09KPxxOL91zoudEv/w6D/Wa7lH2pHKPjoVcZjjYc3M5hSJa74/dXGl42eoBvxzXnpoYIBa+x3ZaNIUgbu6rpQm66RQV4vlAidIY/2GSevmXafhmeW/ItzjZAIm8AtdTwRiqrCJsGcvAJCzSWUKbgSClOWz4G9EPODM1M/iMdmiyi/eoYaTWfQEOgaJBuXaD2hGsi8pC0grEaFBVhsCesUSkgXPuds9SH7QA8bPb/RYD47tvEhJCV6KnSnVbvu1Qe4="

